### ISSUE TITLE
Warnings and errors while trying to build

### ISSUE THREAD

**Issue by frr149** [rentzsch/mogenerator#314]
I just forked the repo to familiarise myself with the code base. So far, while trying to build I get 39 warnings. Is this to be expected?

OTOH, I also get an error complaining about 

       can't open -sectcreate file: $TMPDIR/mogenerator-Info.plist

Can anyone help?

Is there any documentation on getting started with the code base?

**Comment by mbaranowski** [comment]
I ran into the same build error when trying to build master branch with Xcode Version 7.2 (7C68). It looks like the $TMPDIR is not resolved to a system temporary directory when running the link command.

The build error was introduced in this commit: https://github.com/rentzsch/mogenerator/commit/73eac36c065b38e94d8c00e72c32125217b1abb3

My current solution is to revert that commit in my fork of mogenerator, I couldn't find a better way to make $TMPDIR work as expected. Hope this helps.

**Comment by kennebecstars** [comment]
This is an important issue for me because I wanted the updated swift enhancements. So I did a work-around. Here are the steps you need to do and it will build correctly. However, the code for swift in the tests is swift 1.x, so the updates make the tests break, but that is another issue which I could not resolve by looking at the rakefile and the test code. I hope this helps you.

1) Update the "build-mogenerator-Info-plist.sh" script to execute in bash.

-go to the mogenerator target and build phase, run script and change the shell to /bin/bash

2) Change the TMPDIR to a location that is not on the system /var/folders tree. Replace the script "build-mogenerator-Info-plist.sh" to be (be aware that since it is a bourne shell script, leave the 1st line blank):

---

export TMPDIR; TMPDIR=./tmp
if [[ -d "${TMPDIR}" ]]
then
/bin/rm -rf $TMPDIR/mogenerator-Info.plist
mkdir -p ./tmp
fi

/usr/libexec/PlistBuddy \
	-c "Clear" \
	-c "Import :human.h.motemplate templates/human.h.motemplate" \
	-c "Import :human.m.motemplate templates/human.m.motemplate" \
	-c "Import :human.swift.motemplate templates/human.swift.motemplate" \
	-c "Import :machine.h.motemplate templates/machine.h.motemplate" \
	-c "Import :machine.m.motemplate templates/machine.m.motemplate" \
	-c "Import :machine.swift.motemplate templates/machine.swift.motemplate" \
	${TMPDIR}/mogenerator-Info.plist
 
3) change the run script in the build phase to be this:
set -e

/bin/bash build-mogenerator-Info-plist.sh

Now, build using CMD-b or CMD-r. That's maybe gonna get you there, but the test failing worries me because the test conversion from swift 1.x to swift 2.1 in Xcode 7.2.1 is kind of a black hole for me; the changes look minor, but the tests don't work, nonetheless.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
