### ISSUE TITLE
additionalHeaderFileName is needed

### ISSUE THREAD

**Issue by djbe** [rentzsch/mogenerator#331]
### Feature Request

`additionalHeaderFileName` in swift was removed in the last version (commit 9302f55f829556ccebccd1b0f56ff0c6e7f69e04), I'd like to see it back.
### Expected Behavior

`additionalHeaderFileName` used to work.
### Actual Behavior

`additionalHeaderFileName` was removed.
### Additional Information

If you have a transformable property with a `attributeValueClassName` of for example `CLLocation`, the compiler will throw an error if you don't import CoreLocation.

Ideally, in swift, it'd be even better if we could specify multiple `additionalHeaderFileName` (or a comma separated list), as we might have to use multiple imports for different types.

**Comment by rentzsch** [comment]
I agree that `additionalHeaderFileName` should support multiple files somehow (for both Obj-C and Swift).

**Comment by djbe** [comment]
Maybe rename it to `additionalImports`? Or use the `mappedKeyName` syntax, like `additionalImport.1`, `additionalImport.2`, etc...

**Comment by rentzsch** [comment]
`additionalImports` with comma-separated file names sounds great.

**Comment by justin** [comment]
That sounds good to me too.

**Comment by domhof** [comment]
Why was it removed? Is there an alternative way to use enums in Swift? [Using-enums-as-types](https://github.com/rentzsch/mogenerator/wiki/Using-enums-as-types) seems not to work anymore.

**Comment by atomicbird** [comment]
I know this is an old issue, but it's one I'd like to fix, so if anyone's paying attention...

I'm thinking that `additionalHeaderFileName` is misnamed in Swift because you'd normally want to import a module there, not a header file. Of course you might want to do something similar in Objective-C, adding a custom `@import Foo` rather than `#import "Foo.h". So, I'm inclined to add the `additionalImports` as described here, as a comma-separated list that generates appropriate imports for the target language. I think it makes sense to leave `additionalHeaderFileName` as-is, not part of Swift templates at all-- not just for compatibility, but because it supports an Objective-C specific syntax that doesn't really map to Swift.

As an experiment for anyone who messes with `mogenerator` source code-- add this line back in to the Swift template and then run the test suite. Testing fails for Swift because you end up with `import Gender.h` in a Swift source file, which nicely illustrates the problem with just adding `additionalHeaderFileName` back to Swift.

If there are no other comments (and this far after filing, I'm not expecting any, but I'd love to have some feedback) this is what I'm going to do.

**Comment by rentzsch** [comment]
Yup, `additionalHeaderFileName` predates Obj-C support for modules.

`additionalImports` seems like a fine idea.

**Comment by atomicbird** [comment]
Added `additionalImports` in aaea23b
