### ISSUE TITLE
An entity property called 'type' causes App Store rejection

### ISSUE THREAD

**Issue by mbogh** [rentzsch/mogenerator#74]
Hello,

First of all, really nice work. I use this on all my projects which involve CoreData.

Yesterday an app of mine got rejected by Apple due to the use of private APIs. Apple's reply:
"We found the following non-public API in your app:

setPrimitiveType:

If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions."

I don't know what the best solution is but either somekind of warning to the user or renaming the setPrimitiveXXX methods.

Best regards
mbogh

**Comment by seanm** [comment]
I just got around to updating from 1.27 to 1.28 and got a warning message that directed me to this issue.

I can certainly understand the motivation for this change, and I know Apple can be obstinate wrt their App Store, but this change sucks for me, because I use "type" in many places, and have been doing so since 10.5 with no problem (I don't use App Store).  I guess I could rename the next time I change my model, but don't want to do a persistent migration just for such a rename.

Would you accept a patch that adds an option to continue to log the warning but doesn't actually skip the generation?  Thanks.

**Comment by rentzsch** [comment]
@seanm sure, I'd accept such a patch.

**Comment by seanm** [comment]
@rentzsch, I've given it a stab, please review... thanks.
